pekko {
  grpc.client.arktrio {
    host = ${arktrio.common.util.Constants.Config.DefaultHost}
    host = ${?ARKTRIO_CENTER_STATIC_HOST}
    port = ${arktrio.common.util.Constants.Ports.Center}
    port = ${?ARKTRIO_CENTER_STATIC_PORT}
    use-tls = ${arktrio.common.util.Constants.Config.DefaultGrpcClientTls}
    use-tls = ${?ARKTRIO_EDGE_GRPC_CLIENT_TLS}
  }

  loglevel = info
  log-config-on-start = off
  log-dead-letters = 0

  actor.typed {
    default-mailbox {
      mailbox-type = "org.apache.pekko.dispatch.SingleConsumerOnlyUnboundedMailbox"
    }

    mailbox.arktrio.edge.actors {
      adapters {
        EdgeAgentsPutAdapter {
          mailbox-type = "org.apache.pekko.dispatch.SingleConsumerOnlyUnboundedMailbox"
        }
        EdgeNeighborsQueryAdapter {
          mailbox-type = "org.apache.pekko.dispatch.SingleConsumerOnlyUnboundedMailbox"
        }
      }
      sinks {
        Chart {
          mailbox-type = "org.apache.pekko.dispatch.BoundedControlAwareMailbox"
          mailbox-capacity = 10000
          mailbox-push-timeout-time = 0
        }
        Clock {
          mailbox-type = "org.apache.pekko.dispatch.UnboundedControlAwareMailbox"
        }
        Register {
          mailbox-type = "org.apache.pekko.dispatch.UnboundedControlAwareMailbox"
        }
      }
      DeadLetterListener {
        mailbox-type = "org.apache.pekko.dispatch.SingleConsumerOnlyUnboundedMailbox"
      }
      EdgeConfigurator {
        mailbox-type = "org.apache.pekko.dispatch.SingleConsumerOnlyUnboundedMailbox"
      }
    }
  }
}
