arktrio {
  edge {
    dynamic {
      coordinate {
        axis {
          xDirection = East
          yDirection = North
          zDirection = Up
        }
        centerOrigin {
          x = 0.0
          y = 0.0
          z = 0.0
        }
        rotation {
          type = EulerAnglesConfig
          angleUnit = Degree
          rotationMode = Extrinsic
          rotationOrder = XYZ
        }
        lengthUnit = Meter
        speedUnit = MeterPerSecond
      }
      culling {
        edgeCulling = true
        maxFirstAgents = 9
      }
    }
    static {
      edgeIdPrefix = ${arktrio.common.util.Constants.Config.DefaultEdgeIdPrefix}
      edgeIdPrefix = ${?ARKTRIO_EDGE_STATIC_EDGE_ID_PREFIX}
      host = ${arktrio.common.util.Constants.Config.DefaultHost}
      host = ${?ARKTRIO_EDGE_STATIC_HOST}
      port = ${arktrio.common.util.Constants.Ports.Edge}
      port = ${?ARKTRIO_EDGE_STATIC_PORT}
      portAutoIncrement = true
      portAutoIncrement = ${?ARKTRIO_EDGE_STATIC_PORT_AUTO_INCREMENT}
      portAutoIncrementMax = 100
      portAutoIncrementMax = ${?ARKTRIO_EDGE_STATIC_PORT_AUTO_INCREMENT_MAX}
      logLevel = ${arktrio.common.util.Constants.Config.DefaultLogLevel}
      logLevel = ${?ARKTRIO_EDGE_STATIC_LOG_LEVEL}
      logLevelColor = ${arktrio.common.util.Constants.Config.DefaultLogLevelColor}
      logLevelColor = ${?ARKTRIO_EDGE_STATIC_LOG_LEVEL_COLOR}
      logSuppressionList = [
        io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler,
        "sttp.tapir.server.pekkohttp.PekkoHttpServerInterpreter$"
      ]
      actorTimeout = 90ms
      endpointTimeout = 100ms
      clockInitialStashSize = 100
      publishBatchSize = 100
      publishBufferSize = 10000
    }
  }
}
